### ISSUE TITLE
Make an export settings without personal site data

### ISSUE THREAD

**Issue by GeorgyKhairov** [gjbarnard/moodle-theme_adaptable#10]
Hi,

when I report a bug you askme an export settings of the Adaptable theme.

But you notice that it could contain a personal data of the site and ask to remove it.

I wan't to do it myself
I can miss some important information or by mistake delete some important information.

So I ask you to do
add a button (link) which will export only tech data without any personal information.

Replace personal information with any placeholder.

Name this button/link like "Export2support" or something like this.

You will receive settings which will help you.
Users who will send it to you won't be afraid of their personal information.

**Comment by gjb2048** [comment]
Dear @GeorgyKhairov,

Adaptable stores all of its settings at a site administrator level and all of the values of such could be relevant in the replication of an issue.  Besides, how can a computer know what is and what is not explicitly personal information in generic settings not inherently designed for such?  Even I as a human cannot judge 100% what is and what is not your personal information.  Therefore you are responsible as requested.

Gareth
