### ISSUE TITLE
Search in settings for admin

### ISSUE THREAD

**Issue by ktreussi** [gjbarnard/moodle-theme_adaptable#13]
Hello. When an admin try to make a search in Site administration bloc on the the "search in Settings" field, the result is not display correctly.

![Capture d’écran 2023-06-30 à 15 29 13](https://github.com/gjb2048/moodle-theme_adaptable/assets/92855832/97be9684-5307-4e65-a3e1-097196ea4311)

 Moodle: 4.1.4+
 Theme: 401.1.5
 Browser and version: Safari or Firefox

**Comment by gjb2048** [comment]
Cannot replicate:

![Screenshot 2023-06-30 163540](https://github.com/gjb2048/moodle-theme_adaptable/assets/1058419/abb9f4b5-795b-42cf-8878-0e00390a58c6)

**Comment by ktreussi** [comment]
Thanks for the feedback. I found the bug. It came from another plugin. It's ok for me now. I close this bug
