### ISSUE TITLE
Option to default right drawer to open for guests

### ISSUE THREAD

**Issue by VOOM108** [gjbarnard/moodle-theme_adaptable#16]
Edit: I was not sure where to put it, as it is a question first and would be an enhancement secondly depending on the answer. Support was probably the wrong label, but I can't change or remove the issue, so ... 

**Versions (please complete the following information):**
Release 401.1.5, version 2022112306 on Moodle 4.1.5+ (Build: 20230913)

 - Browser and version: any

I have this option checked: 
![image](https://github.com/gjb2048/moodle-theme_adaptable/assets/16562946/51b0fa5d-18aa-4b8f-a8dd-120f46971d5a)

However, for not logged-in users, the blocks sidebar is always closed. (As in Boost 4). Does this mean to show it at all or not, or to show it opened by default? 

If it only means to show it at all - could an option be added to show it opened by default (to show the Login-Box and other highly relevant Blocks)?

**Comment by gjb2048** [comment]
Dear @VOOM108,

Thanks for the issue, 'sidebarnotlogged' doesn't do anything anymore and is meaningless, so I've removed it.

G
