### ISSUE TITLE
the left navigation block drawer  bar cannot be scrolled down/up 

### ISSUE THREAD

**Issue by azizmisir** [gjbarnard/moodle-theme_adaptable#17]
**Describe the bug**
The left navigation block drawer  bar cannot be scrolled down/up 
When clicking on the grey vertical bar with the mouse or touchpad
it works only with center button mouse

**Versions (please complete the following information):**
 - Moodle: [4.1.5]
 - Theme: [401.1.5]

**Comment by gjb2048** [comment]
@azizmisir Cannot replicate.  If you have further evidence, i.e. screencast / screen shots then please provide them, otherwise I'll close the issue.

**Comment by azizmisir** [comment]
![Auswahl_011](https://github.com/gjbarnard/moodle-theme_adaptable/assets/83909892/cc80ab75-6a40-4fa6-a3fb-1354166034d8)

**Comment by gjb2048** [comment]
Cannot replicate:

![Screenshot 2023-10-11 180447](https://github.com/gjbarnard/moodle-theme_adaptable/assets/1058419/29ff99a6-d449-4e53-897d-799573961c44)
