### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by guillogo** [gjbarnard/moodle-theme_adaptable#19]
**Describe the bug**
Hi, the plugin is generating a failing unit test using branch `MOODLE_401`

```
There was 1 error:

1) component_test::test_get_component_classes_in_namespace
Error: Class 'core_external\external_api' not found

/var/www/site/theme/adaptable/classes/output/external.php:39
/var/www/site/lib/classes/component.php:137
/var/www/site/lib/classes/component.php:920
/var/www/site/lib/tests/component_test.php:533
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/site/vendor/phpunit/phpunit/phpunit:97
```

**To Reproduce**
Execute unit test: `vendor/bin/phpunit lib/tests/component_test.php`

**Versions (please complete the following information):**
 - Moodle: 4.1

**Comment by gjb2048** [comment]
Note: M4.1 version issue only.

**Comment by gjb2048** [comment]
Dear @guillogo,

Thanks for the report, the fix is:

![Screenshot 2023-12-06 173841](https://github.com/gjbarnard/moodle-theme_adaptable/assets/1058419/2699258c-2d26-458f-8cc3-e9d0636212fa)

Gareth

**Comment by guillogo** [comment]
Hi @gjb2048 thank you for the fix, can you please add it to `MOODLE_41` branch?

**Comment by gjb2048** [comment]
@guillogo Will do in due course in the next release.  Fix currently in supporters only area.
