### ISSUE TITLE
Activity Icons from custom plugins don't display correctly

### ISSUE THREAD

**Issue by nbartley** [gjbarnard/moodle-theme_adaptable#2]
Because of the color inversion of the icons for activities, this also affects custom icon activities as well, which makes the icons hard to use/identify.

Best example are the Poodll icons when shown, they show up as white but are meaningless because you can't see what the icon was supposed to be.

Moodle 4.1.1 w/ Theme 401.0.1 2022112300

Edit: Please delete. Just found out this isn't Adaptable but base Boost stupidity. Sorry

**Comment by gjb2048** [comment]
The colour inversion is a Boost thing, thus a core issue - unless you can
demonstrate a difference between Boost and Adaptable in this respect.

**Comment by gjb2048** [comment]
Or if no difference, and the core icons are fine, then this is a Poodll
issue.

**Comment by nbartley** [comment]
Again sorry. Not an Adaptable issue, entirely a stupid Boost Issue. Behaves identically between the two. (Looks very stupid)

**Comment by gjb2048** [comment]
Dear Nelson,

If the icon is a Poodll one, then do contact Justin Hunt, he's a lovely guy.

Kind regards,

Gareth
