### ISSUE TITLE
sponsors only

### ISSUE THREAD

**Issue by jzgeorge** [gjbarnard/moodle-theme_adaptable#20]
How can I get the "sponsors only" features, I get this message "These settings and functionlity require the 'local_adaptable' plugin, which is available to sponsors only. " Please help me.

**Versions you are currently using (please complete the following information):**
 - Moodle: 4.3.1

**Comment by gjb2048** [comment]
Dear @jzgeorge,

Please eMail me using the contact details in the Support.md file.

G
