### ISSUE TITLE
4.01 breaks WS API Documentation in MDL ~4.1.8 shows can't find external_api

### ISSUE THREAD

**Issue by dustinbrisebois** [gjbarnard/moodle-theme_adaptable#21]
theme/adaptable/classes/output/external.php currently looks like:

`namespace theme_adaptable\output;

use core_external\external_api;
use core_external\external_function_parameters;
use core_external\external_multiple_structure;
use core_external\external_single_structure;
use core_external\external_value;
use core\external\output\icon_system\load_fontawesome_map;`

where it should look like:

`namespace theme_adaptable\output;

require_once("$CFG->libdir/externallib.php");
require_once("$CFG->libdir/classes/external/output/icon_system/load_fontawesome_map.php");

use external_api;
use external_function_parameters;
use external_multiple_structure;
use external_single_structure;
use external_value;
use core\external\output\icon_system\load_fontawesome_map;`

otherwise you get this:

![image](https://github.com/gjbarnard/moodle-theme_adaptable/assets/16727280/57b09dbb-bf02-4a57-b7c7-5bb6c9e2f544)

when attemping to load the WS API Documentation

**Comment by gjb2048** [comment]
Fix will be in the next release, currently the patch is available to sponsors only.  As this is a code fault, then the simpler patch is:

![Screenshot 2024-01-09 205606](https://github.com/gjbarnard/moodle-theme_adaptable/assets/1058419/3d04fe0f-0cb0-4dd4-a734-9a8779c1f9e5)
