### ISSUE TITLE
Exception : mb_substr(): Argument #3 ($length) must be of type ?int, string given

### ISSUE THREAD

**Issue by lcc77** [gjbarnard/moodle-theme_adaptable#23]
This exception (see title) occurs when I try to enter in a specific course. 

This appended with 5% of courses on my site.

This courses are OK with Boost Theme.

Moodle 4.3 ; Debian 12.

**Comment by gjb2048** [comment]
https://moodle.org/mod/forum/discuss.php?d=455331#p1829662 -> https://moodle.org/mod/forum/discuss.php?d=455331#p1829693.
