### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by Tirmatche** [gjbarnard/moodle-theme_adaptable#24]
How do I become a sponsor, and where is the Support.md file ?

**Versions (please complete the following information):**
 - Moodle: 4.3.3
 - Theme: release 403.1.3
 - Browser and version: Version 122.0.6261.95 (Build official) (64 bits)

**Comment by gjb2048** [comment]
Dear @Tirmatche,

Please see https://github.com/gjbarnard/moodle-theme_adaptable/blob/main/Support.md.

Gareth
