### ISSUE TITLE
The marketing blocks is showed when "Logged in" also if "Logged out" only option selected

### ISSUE THREAD

**Issue by nvallinoto** [gjbarnard/moodle-theme_adaptable#25]
**Describe the bug**
The marketing blocks is showed when user is logged.
**To Reproduce**
1. Go to Marketing block settings.
2. Choose "Logged out" in 'Show the marketing blocks when'
3. Go to home page and log in
4. See error -> the marketing blocks is showed.
   

**Expected behavior**
No marketing blocks should appear after user is logged

**Versions (please complete the following information):**
 - Moodle: [e.g. 4.1]
 - Theme: [e.g. 401.1.10]
 - Browser and version [e.g. Chrome Version 108.0.5359.125 (Official Build) (64-bit) on Windows 10]

Thanks for help.

**Comment by gjb2048** [comment]
Please complete:

Versions (please complete the following information):

Moodle: [e.g. 4.1]
Theme: [e.g. 401.1.10]
Browser and version [e.g. Chrome Version 108.0.5359.125 (Official Build) (64-bit) on Windows 10]

**Comment by nvallinoto** [comment]
Moodle: 4.1
Theme Adaptable: 401.1.10 - 2022112311
Browser version: Google Chrome version 124.0.6367.207 (Build ufficiale) (64 bit) on Windows 10

**Comment by gjb2048** [comment]
Are you saving the settings after you've selected 'Logged out' for the 'marketingvisible' setting?

**Comment by nvallinoto** [comment]
![image](https://github.com/gjbarnard/moodle-theme_adaptable/assets/119407762/5c2c929b-df8a-4567-aba5-84bdf58e12eb)

**Comment by nvallinoto** [comment]
I understood the mistake. It depends on the fact that I added the html in the front page infobox and not in the marketing box.

**Comment by nvallinoto** [comment]
We can close the issue.
