### ISSUE TITLE
Footer information to show on mobile

### ISSUE THREAD

**Issue by Blacksheeprules** [gjbarnard/moodle-theme_adaptable#32]
Release 404.1.0, version 2024032802 on Moodle 4.4.1+ (Build: 20240712)

Latest Chrome

We would like to show the footer info on a mobile phone.

Is there a way to do this using adaptable theme.

Regards,

Mark

**Comment by gjb2048** [comment]
Footer info?  What footer info please Mark?

**Comment by Blacksheeprules** [comment]
Footer title and section 1, 2, and 3 in the footer section of the theme.
They show on a PC but not mobile.

**Comment by gjb2048** [comment]
Still none the wiser, screen shot please.

**Comment by Blacksheeprules** [comment]
Sorry. I sent a screenshot of the adaptable settings page.

I have attached another one of PC view of the footer.

The info in the footer of the attached screen shot shows on a PC and not on
a mobile device.

Regards,

Mark

**Comment by gjb2048** [comment]
No screenshots in the issue Mark -> https://github.com/gjbarnard/moodle-theme_adaptable/issues/32.

**Comment by Blacksheeprules** [comment]
![Capture](https://github.com/user-attachments/assets/5dd41f5f-3329-4079-a0f6-ac43ae14be26)
![Capture1](https://github.com/user-attachments/assets/f8c238b0-1581-4950-bab4-0b293fec81bc)

**Comment by Blacksheeprules** [comment]
Sorry. Do you need anything else?

**Comment by gjb2048** [comment]
Set / change the 'responsivepagefooter' setting.

**Comment by Blacksheeprules** [comment]
Thank-you very much. 
I set https://moodle/admin/search.php?query=responsivepagefooter
to
extra small to extra large and now the footer appears on a phone footer. 
Thanks again!!
