### ISSUE TITLE
Wrong dataset attribute name

### ISSUE THREAD

**Issue by vladaskidanovas** [gjbarnard/moodle-theme_adaptable#4]
**Description**
Hi,
There is an issue with the "Navigation" and "Administration" blocks. For example, let's take the "Administration" block. When we try to expand the "Site administration" drawer, we get an error in DevTools:

```
events.js:1087 Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at _exports.notifyBlockContentUpdated (events.js:1087:230)
    at adminTree.finishExpandingGroup (events.js:3363:787)
    at Tree.expandGroup (events.js:192:3822)
    at Tree.toggleGroup (events.js:192:4416)
    at Tree.handleItemClick (events.js:192:6552)
    at Tree.handleClick (events.js:192:6769)
    at HTMLUListElement.dispatch (jquery-3.6.1.min.js:2:43064)
    at y.handle (jquery-3.6.1.min.js:2:41048)
```
This error causes the JS to stop and leave the loading class in the HTML tag. In our case, we are using custom CSS for the loading class, and the page stuck on loading when we interacted with the "Site administration" drawer.

**Fix**
Change in the /theme/adaptable/classes/output/core_renderer_toolbox.php - line 325:
```
from :$bc->attributes['data-instance-id'] = $bc->blockinstanceid;
to: $bc->attributes['data-instanceid'] = $bc->blockinstanceid;
```

**Expected behavior**
There must be no errors in the DevTools, and the loading class must be removed after successful loading.

**Screenshots**
These screenshots are from vanilla Moodle 4.1 without custom CSS.
![image](https://user-images.githubusercontent.com/38819029/226901275-91d906e9-4da5-4b15-9e91-90203553eed0.png)
![image](https://user-images.githubusercontent.com/38819029/226901384-090bcd4c-5df1-40b2-ae2e-afe614c36779.png)

**Versions (please complete the following information):**
 - Moodle: 4.1
 - Theme:  401.1.0 - latest
 - Browser and version Chrome, Firefox

**JSON settings export**
{"moodle_version":"2022112801","theme_version":"2022112302","enablealerts":"","alerthiddencourse":"warning","enablealertstriptags":"1","alertcount":"1","enablealert1":"","alertkey1":"","alerttext1":"","alerttype1":"info","alertaccess1":"global","alertprofilefield1":"","alertcolorinfo":"#3a87ad","alertbackgroundcolorinfo":"#d9edf7","alertbordercolorinfo":"#bce8f1","alerticoninfo":"info-circle","alertcolorsuccess":"#468847","alertbackgroundcolorsuccess":"#dff0d8","alertbordercolorsuccess":"#d6e9c6","alerticonsuccess":"bullhorn","alertcolorwarning":"#8a6d3b","alertbackgroundcolorwarning":"#fcf8e3","alertbordercolorwarning":"#fbeed5","alerticonwarning":"exclamation-triangle","enableanalytics":"","anonymizega":"1","analyticscount":"1","piwikenabled":"","piwiksiteid":"1","piwikimagetrack":"1","piwiksiteurl":"","piwiktrackadmin":"","frontpageblocksenabled":"0","blocklayoutlayoutrow1":"3-3-3-3","blocklayoutlayoutrow2":"4-4-4-0","blocklayoutlayoutrow3":"3-3-3-3","blocklayoutlayoutrow4":"0-0-0-0","blocklayoutlayoutrow5":"0-0-0-0","frontpageuserblocksenabled":"1","shownavigationblockoncoursepage":"1","unaddableblocks":"","blockbackgroundcolor":"#FFFFFF","blockheaderbackgroundcolor":"#FFFFFF","blockbordercolor":"#59585D","blockregionbackgroundcolor":"transparent","blockheaderbordertopstyle":"dashed","blockheadertopradius":"0","blockheaderbottomradius":"0","blockheaderbordertop":"1px","blockheaderborderleft":"0","blockheaderborderright":"0","blockheaderborderbottom":"0","blockmainbordertopstyle":"none","blockmaintopradius":"0","blockmainbottomradius":"0","blockmainbordertop":"0","blockmainborderleft":"0","blockmainborderright":"0","blockmainborderbottom":"0","fontblockheadersize":"22px","fontblockheaderweight":"400","fontblockheadercolor":"#3A454b","blockicons":"1","blockiconsheadersize":"20px","buttonradius":"5px","buttoncolor":"#51666C","buttonhovercolor":"#009688","buttontextcolor":"#ffffff","buttoncolorscnd":"#51666C","buttonhovercolorscnd":"#009688","buttontextcolorscnd":"#ffffff","buttoncolorcancel":"#c64543","buttonhovercolorcancel":"#e53935","buttontextcolorcancel":"#ffffff","editonbk":"#4caf50","editoffbk":"#f44336","editfont":"#ffffff","edithorizontalpadding":"4px","buttonlogincolor":"#c64543","buttonloginhovercolor":"#e53935","buttonlogintextcolor":"#FFFFFF","buttonloginpadding":"0","buttonloginheight":"24px","buttonloginmargintop":"2px","buttondropshadow":"0","categoryhavecustomheader":"","maincolor":"#3A454b","backcolor":"#FFF","regionmaincolor":"#FFF","linkcolor":"#51666C","linkhover":"#009688","selectiontext":"#000000","selectionbackground":"#00B3A1","loadingcolor":"#00B3A1","msgbadgecolor":"#E53935","messagingbackgroundcolor":"#FFFFFF","headerbkcolor":"#00796B","headertextcolor":"#ffffff","headerbkcolor2":"#009688","marketblockbordercolor":"#e8eaeb","marketblocksbackgroundcolor":"transparent","rendereroverlaycolor":"#3A454b","rendereroverlayfontcolor":"#FFF","tilesbordercolor":"#3A454b","covbkcolor":"#3A454b","covfontcolor":"#ffffff","dividingline":"#ffffff","dividingline2":"#ffffff","breadcrumb":"#f5f5f5","breadcrumbtextcolor":"#444444","messagepopupbackground":"#fff000","messagepopupcolor":"#333333","footerbkcolor":"#424242","footertextcolor":"#ffffff","footertextcolor2":"#ffffff","footerlinkcolor":"#ffffff","forumheaderbackgroundcolor":"#ffffff","forumbodybackgroundcolor":"#ffffff","introboxbackgroundcolor":"#ffffff","coursepagesidebarinfooterenabled":"0","showyourprogress":"none","coursepageblocksliderenabled":"0","coursepageblockactivitybottomenabled":"0","coursepageblocksenabled":"0","coursepageblocklayoutlayouttoprow1":"0-0-0-0","coursepageblocklayoutlayoutbottomrow2":"0-0-0-0","coursesectionbgcolor":"#FFFFFF","coursesectionheaderbg":"#FFFFFF","sectionheadingcolor":"#3A454b","currentcolor":"#d2f2ef","collapsedtopicscoloursenabled":"0","coursesectionheaderborderstyle":"none","coursesectionheaderbordercolor":"#F3F3F3","coursesectionheaderborderwidth":"0","coursesectionheaderborderradiustop":"0","coursesectionheaderborderradiusbottom":"0","coursesectionborderstyle":"solid","coursesectionborderwidth":"1px","coursesectionbordercolor":"#e8eaeb","coursesectionborderradius":"0","coursesectionactivityiconsize":"24px","coursesectionactivityheadingcolour":"#0066cc","coursesectionactivityborderwidth":"2px","coursesectionactivityborderstyle":"dashed","coursesectionactivitybordercolor":"#eeeeee","coursesectionactivityleftborderwidth":"3px","coursesectionactivityassignleftbordercolor":"#0066cc","coursesectionactivityassignbgcolor":"#FFFFFF","coursesectionactivityforumleftbordercolor":"#990099","coursesectionactivityforumbgcolor":"#FFFFFF","coursesectionactivityquizleftbordercolor":"#FF3333","coursesectionactivityquizbgcolor":"#FFFFFF","coursesectionactivitymargintop":"2px","coursesectionactivitymarginbottom":"2px","socialwallbackgroundcolor":"#ffffff","socialwallbordercolor":"#B9B9B9","socialwallbordertopstyle":"solid","socialwallborderwidth":"2px","socialwallsectionradius":"6px","socialwallactionlinkcolor":"#51666C","socialwallactionlinkhovercolor":"#009688","onetopicactivetabbackgroundcolor":"#d9edf7","onetopicactivetabtextcolor":"#000000","dashblocksenabled":"0","dashblocksposition":"abovecontent","dashblocklayoutlayoutrow1":"3-3-3-3","dashblocklayoutlayoutrow2":"4-4-4-0","dashblocklayoutlayoutrow3":"3-3-3-3","dashblocklayoutlayoutrow4":"0-0-0-0","dashblocklayoutlayoutrow5":"0-0-0-0","googlefonts":"","fontname":"sans-serif","fontsubset":"","fontsize":"95%","fontweight":"400","fontcolor":"#333333","topmenufontsize":"14px","menufontsize":"14px","menufontpadding":"20px","fontheadername":"sans-serif","fontheaderweight":"400","fontheadercolor":"#333333","fonttitlename":"sans-serif","fonttitlesize":"48px","fonttitleweight":"400","fonttitlecolor":"#ffffff","fonttitlecolorcourse":"#ffffff","moodledocs":"1","footerblocksplacement":"1","showfooterblocks":"1","footerlayoutrow1":"0-0-0-0","footerlayoutrow2":"0-0-0-0","footerlayoutrow3":"0-0-0-0","hidefootersocial":"1","gdprbutton":"none","footnote":"","frontpagerenderer":"2","frontpagenumbertiles":"4","frontpagerendererdefaultimage":"","tilesshowcontacts":"1","tilesshowallcontacts":"0","tilescontactstitle":"1","covhidebutton":"0","enableavailablecourses":"inherit","sliderenabled":"0","sliderfullscreen":"0","slidermargintop":"20px","slidermarginbottom":"20px","slideroption2":"slider1","slidercount":"3","p1":"","p1url":"","p1cap":"","p2":"","p2url":"","p2cap":"","p3":"","p3url":"","p3cap":"","enableticker":"1","enabletickermy":"1","tickerwidth":"","newstickercount":"1","tickertext1":"","tickertext1profilefield":"","headerbgimage":"","displaylogin":"button","showusername":"1","logo":"","pageheaderheight":"72px","coursepageheaderhidesitetitle":"0","sitetitle":"default","sitetitletext":"","enableheading":"fullname","breadcrumbdisplay":"breadcrumb","coursetitlemaxwidth":"20","breadcrumbhome":"icon","breadcrumbseparator":"angle-right","headersearchandsocial":"searchmobilenav","searchboxpadding":"0 0 10px 0","enablesavecanceloverlay":"1","headerstyle":"style1","pageheaderlayout":"original","pageheaderlayouttwo":"original","enablemenus":"1","menuslinkright":"1","menuslinkicon":"fa-link","disablemenuscoursepages":"1","menusession":"1","menusessionttl":"30","menuuseroverride":"","menuoverrideprofilefield":"topmenusettings","topmenuscount":"1","newmenu1title":"Menu 1","newmenu1":"","newmenu1requirelogin":"","newmenu1field":"","socialsize":"37px","socialpaddingside":"16","socialpaddingtop":"0%","socialtarget":"_self","socialiconlist":"","usernameposition":"left","hideinforum":"","enablemy":"1","enableprofile":"1","enableeditprofile":"1","enablecalendar":"1","enableprivatefiles":"","enablegrades":"1","enablebadges":"","enablepref":"1","enablenote":"","enableblog":"","enableposts":"","enablefeed":"","enableaccesstool":"","homebk":"","blockside":"0","fullscreenwidth":"98%","standardscreenwidth":"standard","sidebarnotlogged":"1","emoticonsize":"16px","infoiconcolor":"#5bc0de","dangericoncolor":"#d9534f","tabbedlayoutcoursepage":"0","tabbedlayoutcoursepagelink":"","tabbedlayoutcoursepagetabcolorselected":"#06c","tabbedlayoutcoursepagetabcolorunselected":"#eee","tabbedlayoutcoursepagetabpersistencetime":"30","tabbedlayoutdashboard":"0","tabbedlayoutdashboardcolorselected":"#06c","tabbedlayoutdashboardcolorunselected":"#eee","tabbedlayoutdashboardtab1condition":"","tabbedlayoutdashboardtab2condition":"","responsiveheader":"d-none d-lg-block","responsivesocial":"d-none d-lg-block","responsivesocialsize":"34px","responsivelogo":"d-none d-lg-inline-block","responsivecoursetitle":"d-none d-lg-inline-block","responsivesectionnav":"1","responsiveticker":"d-none d-lg-block","responsivebreadcrumb":"d-none d-md-flex","responsiveslider":"d-none d-lg-block","responsivepagefooter":"d-none d-lg-block","mobilemenubkcolor":"#F9F9F9","mobileslidebartabbkcolor":"#F9F9F9","mobileslidebartabiconcolor":"#000000","loginbgimage":"","loginbgstyle":"cover","loginbgopacity":"0.8","loginheader":"1","loginfooter":"1","logintextboxtop":"","logintextboxbottom":"","infobox":"","infobox2":"","infoboxfullscreen":"","frontpagemarketenabled":"","frontpagemarketoption":"covtiles","marketlayoutrow1":"3-3-3-3","marketlayoutrow2":"0-0-0-0","marketlayoutrow3":"0-0-0-0","marketlayoutrow4":"0-0-0-0","marketlayoutrow5":"0-0-0-0","stickynavbar":"1","enablehome":"1","enablehomeredirect":"1","enablemyhome":"1","enableevents":"1","enablethiscourse":"1","enablecoursesections":"1","enablecompetencieslink":"","enablezoom":"1","defaultzoom":"wide","enablezoomshowtext":"1","enableshowhideblocks":"1","enableshowhideblockstext":"1","enablenavbarwhenloggedout":"","editsettingsbutton":"cog","editcognocourseupdate":"1","displayeditingbuttontext":"1","enablemysites":"excludehidden","enablemysitesrestriction":"","mycoursesmenulimit":"20","mysitesmaxlength":"30","mysitessortoverride":"myoverview","mysitessortoverridefield":"","mysitesmenudisplay":"shortcodehover","chiddenicon":"eye-slash","cfrozenicon":"snowflake-o","cneveraccessedicon":"exclamation-circle","cdefaulticon":"graduation-cap","displayparticipants":"1","displaygrades":"1","disablecustommenu":"","enabletoolsmenus":"","toolsmenuscount":"1","toolsmenu1title":"Tools","toolsmenu1":"","toolsmenu1field":"","helptarget":"_blank","helplinkscount":"2","menubkcolor":"#ffffff","menufontcolor":"#222222","menuhovercolor":"#00B3A1","menubordercolor":"#00B3A1","navbardisplayicons":"1","navbardisplaysubmenuarrow":"","navbardropdownborderradius":"0","navbardropdownhovercolor":"#EEE","navbardropdowntextcolor":"#007","navbardropdowntexthovercolor":"#000","navbardropdowntransitiontime":"0.2s","printpageorientation":"landscape","printbodyfontsize":"11pt","printmargin":"2cm 1cm 2cm 2cm","printlineheight":"1.2","templatessel":"","customcoursetitle":"","customcoursesubtitle":"","enabletabbedprofile":"1","enabledtabbedprofileeditprofilelink":"1","enabledtabbedprofileuserpreferenceslink":"1","customcss":"","jssection":"","jssectionrestricted":"","jssectionrestrictedprofilefield":"","jssectionrestricteddashboardonly":"1","analyticstext1":"","analyticsprofilefield1":"","sliderh3color":"#ffffff","sliderh4color":"#ffffff","slidersubmitcolor":"#ffffff","slidersubmitbgcolor":"#51666C","enablehelp1":"","helplinktitle1":"","helpprofilefield1":"","enablehelp2":"","helplinktitle2":"","helpprofilefield2":"","dimmedtextcolor":"#6a737b","market1":"","market2":"","market3":"","market4":"","hvpcustomcss":"","buttonfocuscolor":"#0F6CC0","buttonfocuscoloropacity":"0.75","courseindexitemcolor":"#495057","courseindexitemhovercolor":"#000000","courseindexpageitemcolor":"#ffffff","courseindexpageitembgcolor":"#0f6cbf"}

**Comment by gjb2048** [comment]
@vladaskidanovas That line is already '$bc->attributes['data-instanceid'] = $bc->blockinstanceid;' and has been since the M3.6 version at least!  Check that someone hasn't been messing with your install.
