### ISSUE TITLE
Grader report hides last name of students

### ISSUE THREAD

**Issue by GeorgyKhairov** [gjbarnard/moodle-theme_adaptable#9]
Hi,
I found bug when the grader report hides last name of students.
I think the bug is in the formatting of layout table with the list of students.
The first column contains student avatar, name and surname of students.

I reported Moodle bug (https://tracker.moodle.org/browse/MDL-76060).
I was appeared under all installed themes.
Some time ago it was resolved and not appeared.

On new version of Adaptable theme the error appeared again.
Under classic Moodle theme it does not appeared.

Moodle 4.1.3plus [Moodle](http://moodle.org/) [4.1.3+ (Build: 20230504)](http://docs.moodle.org/dev/Releases)

Adaptable theme 401.1.5

 See behavior in the film attached

Link to the film https://drive.google.com/file/d/1RjSbcP_QJJjLmyUwohA0iPXQwR-H0O4v/view?usp=share_link

One more
when the corse has a lot of topics you show horizontal scroll bar at the bottom of the list of students.
Add the same horizontal scroll bar at the top of the student`s list, above the topic titles.

It will make more convenient the work of teacher when he should mark a lot of students when the course has a lot of topics

**To Reproduce**

Open Grader Report
[https://[moodle-site]/grade/report/grader/index.php?id=[course-id]]

When wide of this column is not enougth to display full name of students the line is wrapped.

When you use horisontal scroll bar, move it to the right to see all of the assessed elements the beginning of first column hides and hide part of information about the name of students.
The beginning of the student surnames and students avatars are hidden.

**Expected behavior**
The name of students does not hide.

**Screenshots**
Link to the film https://drive.google.com/file/d/1RjSbcP_QJJjLmyUwohA0iPXQwR-H0O4v/view?usp=share_link

**Versions (please complete the following information):**
Moodle 4.1.3plus [Moodle](http://moodle.org/) [4.1.3+ (Build: 20230504)](http://docs.moodle.org/dev/Releases)
Adaptable theme 401.1.5
Browser and version FireFox version 113.0.2 and Google Chrome version 109.0.5414.141 on Windows 8.1
Bug reported by the teachers who use different browsers

**JSON settings export**
Settings are the same as they was before.
But two month ago (6 April 2023) with the latest (at that time) verson Mooodle and Adaptable theme all was OK
It was  Moodle 4.1.2 and latest Adaptable theme

**Additional context**
Read the bug https://tracker.moodle.org/browse/MDL-76060
Previous screenshots are included in that bug.

**Comment by gjb2048** [comment]
@GeorgyKhairov,

But this has already been reported and fixed -> https://moodle.org/mod/forum/discuss.php?d=447234.

Gareth

**Comment by GeorgyKhairov** [comment]
Hi,
actually it does not fixed.

**Comment by GeorgyKhairov** [comment]
Read carefully  -> https://moodle.org/mod/forum/discuss.php?d=447234.
It was written it will be fixxed.
But it is not fixed now
